version: "3"
services:
  # mongo-express:
  #   # env_file:
  #   #   - ./env/mongo-express.env
  #   image: mongo-express
  #   container_name: nest-nextjs-mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=root
  #     - ME_CONFIG_MONGODB_URL=mongodb://root:root@mongodb:27017
  #   networks:
  #     - nest-next-ecomm
  # mongodb:
  #     # env_file:
  #     #   - ./env/mongo.env
  #     image: mongo:5
  #     container_name: nest-next-mongo
  #     ports:
  #       - "27018:27017"
  #     environment:
  #       - MONGO_INITDB_ROOT_USERNAME=root
  #       - MONGO_INITDB_ROOT_PASSWORD=root
  #     volumes:
  #       - ./data/mongo:/data
  #     networks:
  #       - nest-next-ecomm
  redis:
    image: redis:latest
    container_name: nest-nextjs-redis-container
    volumes:
    - ./data/redis-data:/data
    privileged: true
    ports:
      - "6380:6379"
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: nest-nextjs-redis-commander
    environment:
      - REDIS_PORT=6379
      - REDIS_HOST=redis
    ports:
      - "8000:8081"
    depends_on:
      - redis
networks:
  nest-next-ecomm:
    driver: bridge
