export class EnvironmentConstants {
  static PORT = 'PORT';
  static DATABASE_URL = 'DATABASE_URL';
  static JWT_ACCESS_TOKEN_SECRET = 'JWT_ACCESS_TOKEN_SECRET';
  static JWT_ACCESS_TOKEN_EXPIRES_IN = 'JWT_ACCESS_TOKEN_EXPIRES_IN';
  static REDIS_HOST = 'REDIS_HOST';
  static REDIS_PORT = 'REDIS_PORT';
  static USER_TOKEN_CACHE_KEY = 'USER_TOKEN_CACHE_KEY';
  static COOKIE_JWT_ACCESS_TOKEN_KEY = 'COOKIE_JWT_ACCESS_TOKEN_KEY';
  static COOKIE_REFRESH_TOKEN_KEY = 'COOKIE_REFRESH_TOKEN_KEY';
  static JWT_REFRESH_TOKEN_SECRET = 'JWT_REFRESH_TOKEN_SECRET';
  static JWT_REFRESH_TOKEN_EXPIRES_IN = 'JWT_REFRESH_TOKEN_EXPIRES_IN';
  static DUPLICATE_ERROR_KEY = 'DUPLICATE_ERROR_KEY';
  static FRONTNED_URL = 'FRONTNED_URL';
  static PASSWORD_RESET_TOKEN_SECRET = 'PASSWORD_RESET_TOKEN_SECRET';
  static PASSWORD_RESET_TOKEN_EXPIRES_IN = 'PASSWORD_RESET_TOKEN_EXPIRES_IN';
}
